# Writing workflows for main.yml 
# This is main.yml

name: DevSecOps Basic Pipeline

on: [push]

jobs:
  First_build:
    runs-on: ubuntu-latest
    steps:
    - name: Create dependncy jobs and output of one to other
      run: echo "Input for Test Job" > test_input.txt

    - name: Pass the file to test job
      uses: actions/upload-artifact@v2
      with:
        name: testinputfile
        path: test_input.txt
      if: always()     
  
  First_test:
    runs-on: ubuntu-latest
    needs: First_build

    steps:
    - name: Download the file from previous job
      uses: actions/download-artifact@v2
      with:
        name: testinputfile
        
    - name: Check if file has been created
      run: cat test_input.txt
        